### ISSUE TITLE
<noscript>-tag missing

### ISSUE THREAD

**Issue by Jonta** [HappyDustbunny/FuzzyPlan#1]
Hence buttons not working when blocking JS, without indication as to why. =)

**Comment by HappyDustbunny** [comment]
Oups. Not checking GitHub often. Hope this is resolved by now as only beta testing remains :-)

**Comment by Jonta** [comment]
@HappyDustbunny Still experiencing this at http://madshorn.operamail.com/planner/add.html

**Comment by HappyDustbunny** [comment]
Ahh, that's a deep link to part of the old page. 
At the start page at the Operamail hosting there is a redirect to my new site with a nearly working version is hosted.

In the future the planner will live on fuzzyplan.madshorn.dk/index.html where the latest beta is currently living.
It is now a PWA that can be installed and launched from the home screen. It freezes occasionally when offline, but mostly works as intended now :-)

Thanks for reminding me to update/remove the old stuff at operamail :-)
